basePath: /
definitions:
  delete_offer.DeleteOfferRequest:
    properties:
      offer_id:
        type: string
    required:
    - offer_id
    type: object
  github_com_4udiwe_subscription-service_internal_entity.Offer:
    properties:
      createdAt:
        type: string
      durationMonths:
        type: integer
      id:
        type: string
      name:
        type: string
      price:
        type: integer
      updatedAt:
        type: string
    type: object
  internal_handler_delete_sub.DeleteSubscriptionRequest:
    properties:
      subscription_id:
        type: string
    required:
    - subscription_id
    type: object
  internal_handler_get_offers.GetAllOffersResponse:
    properties:
      offers:
        items:
          $ref: '#/definitions/github_com_4udiwe_subscription-service_internal_entity.Offer'
        type: array
      page:
        type: integer
      page_size:
        type: integer
      total_items:
        type: integer
      total_pages:
        type: integer
    type: object
  internal_handler_get_subs.GetAllSubscriptionsResponse:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      subscriptions:
        items:
          $ref: '#/definitions/internal_handler_get_subs.Subscription'
        type: array
      total_items:
        type: integer
      total_pages:
        type: integer
    type: object
  internal_handler_get_subs.Subscription:
    properties:
      end_date:
        type: string
      offer_name:
        type: string
      price:
        type: integer
      start_date:
        type: string
      subscription_id:
        type: string
      user_id:
        type: string
    type: object
  internal_handler_get_subs_by_user.GetSubscriptionsByUserRequest:
    properties:
      page:
        type: integer
      pageSize:
        type: integer
      user_id:
        type: string
    required:
    - user_id
    type: object
  internal_handler_get_subs_by_user.GetSubscriptionsByUserResponse:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      subscriptions:
        items:
          $ref: '#/definitions/internal_handler_get_subs_by_user.Subscription'
        type: array
      total_items:
        type: integer
      total_pages:
        type: integer
    type: object
  internal_handler_get_subs_by_user.Subscription:
    properties:
      end_date:
        type: string
      offer_name:
        type: string
      price:
        type: integer
      start_date:
        type: string
      subscription_id:
        type: string
      user_id:
        type: string
    type: object
  internal_handler_get_subs_by_user_subname.GetSubsByUserAndServiceNameRequest:
    properties:
      end_date:
        type: string
      offer_name:
        type: string
      page:
        type: integer
      pageSize:
        type: integer
      start_date:
        type: string
      user_id:
        type: string
    required:
    - offer_name
    - user_id
    type: object
  internal_handler_get_subs_by_user_subname.GetSubsByUserAndServiceNameResponse:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      subscriptions:
        items:
          $ref: '#/definitions/internal_handler_get_subs_by_user_subname.Subscription'
        type: array
      total_items:
        type: integer
      total_pages:
        type: integer
      total_price:
        type: integer
    type: object
  internal_handler_get_subs_by_user_subname.Subscription:
    properties:
      end_date:
        type: string
      offer_name:
        type: string
      price:
        type: integer
      start_date:
        type: string
      subscription_id:
        type: string
      user_id:
        type: string
    type: object
  internal_handler_post_sub_by_name.PostSubscriptionByNameRequest:
    properties:
      end_date:
        type: string
      price:
        minimum: 0
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    required:
    - price
    - service_name
    - start_date
    - user_id
    type: object
  internal_handler_post_sub_by_name.PostSubscriptionByNameResponse:
    properties:
      end_date:
        type: string
      offer_name:
        type: string
      price:
        type: integer
      start_date:
        type: string
      subscription_id:
        type: string
      user_id:
        type: string
    type: object
  internal_handler_post_sub_by_offer_id.PostSubscriptionByOfferIDRequest:
    properties:
      offer_id:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    required:
    - offer_id
    - start_date
    - user_id
    type: object
  internal_handler_post_sub_by_offer_id.PostSubscriptionByOfferIDResponse:
    properties:
      end_date:
        type: string
      offer_name:
        type: string
      price:
        type: integer
      start_date:
        type: string
      subscription_id:
        type: string
      user_id:
        type: string
    type: object
  post_offer.PostOfferRequest:
    properties:
      duration_months:
        minimum: 1
        type: integer
      price:
        minimum: 0
        type: integer
      service_name:
        type: string
    required:
    - duration_months
    - price
    - service_name
    type: object
  post_offer.PostOfferResponse:
    properties:
      created_at:
        type: string
      duration_months:
        type: integer
      offer_id:
        type: string
      price:
        type: integer
      service_name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: sharifkulov.work@gmail.com
  description: Сервис для агрегации онлайн-подписок (тестовое задание).
  title: Subscriptions Service
  version: "1.0"
paths:
  /offers:
    delete:
      consumes:
      - application/json
      description: Удаление предложения по ID. Если есть активные подписки на это
        предложение, оно не будет удалено.
      parameters:
      - description: offer to delete
        in: body
        name: offer
        required: true
        schema:
          $ref: '#/definitions/delete_offer.DeleteOfferRequest'
      responses:
        "202":
          description: No Content
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Удаление предложения
      tags:
      - offers
    get:
      consumes:
      - application/json
      description: Получение списка всех офферов
      parameters:
      - default: 1
        description: Номер страницы
        in: query
        name: page
        type: integer
      - default: 10
        description: Размер страницы
        in: query
        maximum: 100
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handler_get_offers.GetAllOffersResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Получение всех офферов
      tags:
      - offers
    post:
      consumes:
      - application/json
      description: Создание нового предложения с указанными параметрами
      parameters:
      - description: Offer details
        in: body
        name: offer
        required: true
        schema:
          $ref: '#/definitions/post_offer.PostOfferRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/post_offer.PostOfferResponse'
        "409":
          description: Conflict
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Создание нового предложения
      tags:
      - offers
  /subscriptions:
    delete:
      consumes:
      - application/json
      description: Удаление подписки по ID. Не удаляет предложение, на которое была
        оформлена подписка.
      parameters:
      - description: subscription to delete
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/internal_handler_delete_sub.DeleteSubscriptionRequest'
      responses:
        "202":
          description: No Content
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Удаление подписки
      tags:
      - subscriptions
    get:
      consumes:
      - application/json
      description: Получение списка всех подписок
      parameters:
      - default: 1
        description: Номер страницы
        in: query
        name: page
        type: integer
      - default: 10
        description: Размер страницы
        in: query
        maximum: 100
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handler_get_subs.GetAllSubscriptionsResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Получение всех подписок
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Создание новой подписки для пользователя с возможностью создания
        нового предложения, если оно не существует
      parameters:
      - description: subscription info
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/internal_handler_post_sub_by_name.PostSubscriptionByNameRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_handler_post_sub_by_name.PostSubscriptionByNameResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Создание новой подписки
      tags:
      - subscriptions
  /subscriptions/by-offer:
    post:
      consumes:
      - application/json
      description: Создание новой подписки для пользователя по ID предложения, полученного
        из ендпоинта всех предложений
      parameters:
      - description: subscription info
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/internal_handler_post_sub_by_offer_id.PostSubscriptionByOfferIDRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_handler_post_sub_by_offer_id.PostSubscriptionByOfferIDResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Создание новой подписки по ID предложения
      tags:
      - subscriptions
  /subscriptions/by-user:
    get:
      consumes:
      - application/json
      description: Получение списка подписок для указанного пользователя
      parameters:
      - description: user ID
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/internal_handler_get_subs_by_user.GetSubscriptionsByUserRequest'
      - default: 1
        description: Номер страницы
        in: query
        name: page
        type: integer
      - default: 10
        description: Размер страницы
        in: query
        maximum: 100
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handler_get_subs_by_user.GetSubscriptionsByUserResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Получение подписок по ID пользователя
      tags:
      - subscriptions
  /subscriptions/by-user-and-subname:
    get:
      consumes:
      - application/json
      description: Получение списка подписок для указанного пользователя и названия
        подписки с возможностью фильтрации по дате начала и окончания
      parameters:
      - description: user ID and subscription name
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/internal_handler_get_subs_by_user_subname.GetSubsByUserAndServiceNameRequest'
      - default: 1
        description: Номер страницы
        in: query
        name: page
        type: integer
      - default: 10
        description: Размер страницы
        in: query
        maximum: 100
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handler_get_subs_by_user_subname.GetSubsByUserAndServiceNameResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Получение подписок по ID пользователя и названию подписки
      tags:
      - subscriptions
schemes:
- http
swagger: "2.0"
